apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daveBackend.fullname" . }}-email
  labels: 
    {{- include "daveBackend.labels" . | nindent 4 }}
data:
  {{- with .Values.extraEnvVars.email }}
    {{- toYaml . | nindent 12 }}
  {{- end}}
