apiVersion: v2
name: kf-app-eai
description: TODO
type: application
version: 0.1.0
appVersion: "0.0.9"
maintainers:
  - name: maximilian-zollbrecht 
    email: max.zollbrecht@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/kf-app-eai
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"