apiVersion: v1
kind: Service
metadata:
  name: {{ include "daveFrontend.fullname" . }}
  labels:
    {{- include "daveFrontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}

  selector:
    {{- include "daveFrontend.selectorLabels" . | nindent 4 }}
