apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daveAdminPortal.fullname" . }}
  labels: 
    {{- include "daveAdminPortal.labels" . | nindent 4 }}
data:
  {{- with .Values.extraEnvVars }}
    {{- toYaml . | nindent 12 }}
  {{- end}}
