apiVersion: v2
name: refarch-template
description: Helm chart template for deploying it@M Reference Architecture based applications.
type: application
version: 1.0.0
home: https://github.com/it-at-m/helm-charts/tree/main/charts/refarch-template
icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
dependencies:
  - name: backend
    version: 1.0.0
  - name: frontend
    version: 1.0.0
