apiVersion: v2
name: admin-portal
description: DAVe traffic counting plattform, admin-portal
type: application
version: 0.0.1
appVersion: "v1.0.0"
maintainers:
  - name: Martin Bayr
    email: martymcfly333@gmail.com
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/admin-portal
#icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-admin-portal"
