apiVersion: v2
name: dave
description: DAVe traffic counting plattform
type: application
version: 0.0.1
appVersion: "v1.0.0"
# appVersion: "main-ls1" hier? 
maintainers:
  - name: Martin Bayr
    email: martymcfly333@gmail.com
  - name: Klaus Mueller
    email: klml@muenchen.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave
#icon: https://opensource.muenchen.de/assets/itm-logo-256.png
sources:
  - "https://github.com/it-at-m/helm-charts"
dependencies:
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 19.17.0
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.3.0
  - name: backend
    version: "*"
  - name: frontend
    version: "*"
  - name: admin-portal
    version: "*"
  - name: selfservice-portal
    version: "*"
  - name: eai
    version: "*"
