apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refarch-gateway.fullname" . }}
  labels: 
    {{- include "refarch-gateway.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- tpl ( toYaml .Values.applicationYML) . | nindent 4 }}
